
async function getYouTubeAutoGeneratedSubtitles(videoId) {
    const url = `https://www.youtube.com/watch?v=${videoId}`;
    try {
        const response = await fetch(url);
        const text = await response.text();

        // Extract the JSON metadata containing the caption tracks
        const ytInitialPlayerResponseMatch = text.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/);
        if (ytInitialPlayerResponseMatch) {
            const ytInitialPlayerResponse = JSON.parse(ytInitialPlayerResponseMatch[1]);
            const captionTracks = ytInitialPlayerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks;

            if (captionTracks) {
                const englishTrack = captionTracks.find(track => track.languageCode === 'en' && track.kind === 'asr');
                if (englishTrack) {
                    const subtitlesUrl = englishTrack.baseUrl;
                    const subtitleResponse = await fetch(subtitlesUrl);
                    const subtitles = await subtitleResponse.text();
                    console.log(subtitles);
                } else {
                    console.log("No auto-generated English subtitles found for this video.");
                }
            } else {
                console.log("No captions found for this video.");
            }
        } else {
            console.log("No subtitle metadata found for this video.");
        }
    } catch (error) {
        console.error("An error occurred:", error);
    }
}

function getYouTubeVideoId() {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get('v');
}


//javascript:(function(){var script=document.createElement('script');script.src='YOUR_SCRIPT_URL_HERE';document.head.appendChild(script);})();
// Example usage
//const videoId = "VIDEO_ID_HERE"; // Replace with your YouTube video ID
//getYouTubeAutoGeneratedSubtitles(videoId);
